services:
  backend:
    build: ./backend
    container_name: recipe-backend
    restart: unless-stopped
    ports:
      - "8347:8347"
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8347/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: recipe-frontend
    restart: unless-stopped
    ports:
      - "3742:3742"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8347
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3742/', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  recipe-network:
    driver: bridge